name = "Discord Command Executor"
description = "Executa comandos recebidos via Discord usando um arquivo intermediário."
author = "Daniel Lucas"
version = "1.0"
api_version = 10
dst_compatible = true
server_only_mod = true
client_only_mod = false
all_clients_require_mod = false
